#!/bin/bash
/sbin/ifconfig ${1##/*/} 192.168.2.1
/sbin/iptables -A POSTROUTING -t nat -s 192.168.2.0/24 ! -d 192.168.2.0/24 -j MASQUERADE
/sbin/iptables -t nat -s 192.168.1.0/24 ! -d 192.168.1.0/24 -A POSTROUTING -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward
